lang: es 
website:
  cookie-consent: true

project:
  type: book  
  output-dir: docs  

  
book:
  title: "Python intermedio, LaSalle, Oaxaca"
  # version: 0.9.1
  navbar:
    search: True
  sidebar:
    menu: True
    collapse-level: 1
    border: true
    logo: img/logo_ier.png
  page-footer:
    center: "[Repositorio](https://github.com/altamarmx/analista)"
    background: "#f8f9fa"
  repo-url: https://github.com/altamarmx/python-basico-lasalle/
  chapters:
    - index.qmd 
    # - datos.qmd
    - part: 'Día Uno' #notebooks/semanaUno/semana1.qmd
      chapters:         
        - notebooks/01/001_instala_python.qmd
    - part: 'Día Dos' #notebooks/semanaUno/semana1.qmd
      chapters:         
        - notebooks/02/002_a_Shiny.qmd 
format:
  html:
    theme: 
      light: dark
      dark: slate
    code-link: true
